// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_O23szlX31wp9IcQIojqg1I8cvc9uaak',
    appId: '1:243588036198:web:1aa7ed2e07bba463725fa7',
    messagingSenderId: '243588036198',
    projectId: 'ecommerceapp-f77c5',
    authDomain: 'ecommerceapp-f77c5.firebaseapp.com',
    storageBucket: 'ecommerceapp-f77c5.firebasestorage.app',
    measurementId: 'G-S80VMXCP8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi72KzKKY7Kh-Kand-ysKoLFBhA2FS2r4',
    appId: '1:243588036198:android:e437ac8a6122ce7e725fa7',
    messagingSenderId: '243588036198',
    projectId: 'ecommerceapp-f77c5',
    storageBucket: 'ecommerceapp-f77c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjNND1HEZGbi1D_xJ21ogYeblrS6uzPtg',
    appId: '1:243588036198:ios:be7ebc72862f9628725fa7',
    messagingSenderId: '243588036198',
    projectId: 'ecommerceapp-f77c5',
    storageBucket: 'ecommerceapp-f77c5.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjNND1HEZGbi1D_xJ21ogYeblrS6uzPtg',
    appId: '1:243588036198:ios:be7ebc72862f9628725fa7',
    messagingSenderId: '243588036198',
    projectId: 'ecommerceapp-f77c5',
    storageBucket: 'ecommerceapp-f77c5.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_O23szlX31wp9IcQIojqg1I8cvc9uaak',
    appId: '1:243588036198:web:b04523c118ea6d09725fa7',
    messagingSenderId: '243588036198',
    projectId: 'ecommerceapp-f77c5',
    authDomain: 'ecommerceapp-f77c5.firebaseapp.com',
    storageBucket: 'ecommerceapp-f77c5.firebasestorage.app',
    measurementId: 'G-YV8FTEH03R',
  );
}
